version: 2.1
setup: true
orbs: 
  path-filtering: circleci/path-filtering@0.1.3

jobs:
  setup_job:
    executor: path-filtering/default
    steps:
      - checkout
      - path-filtering/filter:
        name: check-files
        mapping: | 
          patha/.* run-path-a true
          pathb/.* run-path-b true
        base-revision: << pipeline.git.base_revision >> 
        config-path: .circleci/continue-config.yml
        
